/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package payroll;

import java.io.File;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Casey
 */
public class PayrollGUI extends javax.swing.JFrame {

    /**
     * Creates new form PayrollGUI
     */
    public PayrollGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        parseRouteTab = new javax.swing.JPanel();
        btnBrowseRoute = new javax.swing.JButton();
        btnParseRoute = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        inputFileTextField = new javax.swing.JTextField();
        parseEquipmentTab = new javax.swing.JPanel();
        parsePrintRouteTab = new javax.swing.JPanel();
        closeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Payroll");

        parseRouteTab.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnBrowseRoute.setText("Browse");
        btnBrowseRoute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseRouteActionPerformed(evt);
            }
        });

        btnParseRoute.setText("Parse Selected File");
        btnParseRoute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnParseRouteActionPerformed(evt);
            }
        });

        jLabel1.setText("Select an Exported Route File");

        javax.swing.GroupLayout parseRouteTabLayout = new javax.swing.GroupLayout(parseRouteTab);
        parseRouteTab.setLayout(parseRouteTabLayout);
        parseRouteTabLayout.setHorizontalGroup(
            parseRouteTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(parseRouteTabLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(parseRouteTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnParseRoute)
                    .addComponent(btnBrowseRoute, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputFileTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(271, Short.MAX_VALUE))
        );
        parseRouteTabLayout.setVerticalGroup(
            parseRouteTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(parseRouteTabLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(14, 14, 14)
                .addComponent(inputFileTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBrowseRoute)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnParseRoute)
                .addContainerGap(273, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Parse Route", parseRouteTab);

        javax.swing.GroupLayout parseEquipmentTabLayout = new javax.swing.GroupLayout(parseEquipmentTab);
        parseEquipmentTab.setLayout(parseEquipmentTabLayout);
        parseEquipmentTabLayout.setHorizontalGroup(
            parseEquipmentTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 755, Short.MAX_VALUE)
        );
        parseEquipmentTabLayout.setVerticalGroup(
            parseEquipmentTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 413, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Parse Equipment", parseEquipmentTab);

        javax.swing.GroupLayout parsePrintRouteTabLayout = new javax.swing.GroupLayout(parsePrintRouteTab);
        parsePrintRouteTab.setLayout(parsePrintRouteTabLayout);
        parsePrintRouteTabLayout.setHorizontalGroup(
            parsePrintRouteTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 755, Short.MAX_VALUE)
        );
        parsePrintRouteTabLayout.setVerticalGroup(
            parsePrintRouteTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 413, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Parse PrintRoute", parsePrintRouteTab);

        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(closeButton)
                .addContainerGap())
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(closeButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_closeButtonActionPerformed

    // TODO: CREATE BROWSE FOR EXCEL METHOD TO REUSE *************************
    private void btnBrowseRouteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseRouteActionPerformed
        // Set filter to only see excel files
        FileFilter filter = new FileNameExtensionFilter("Excel Files", "xls", "xlsx");
        chooser = new JFileChooser();
        chooser.addChoosableFileFilter(filter);
        chooser.setFileFilter(filter);
        int returnVal = chooser.showOpenDialog(PayrollGUI.this);
        
        if(returnVal == JFileChooser.APPROVE_OPTION){
            routeFile = chooser.getSelectedFile();
            routeFileName = chooser.getSelectedFile().getAbsolutePath();
            inputFileTextField.setText(routeFileName);
        }
        else{
            System.out.println("No File Selected");
        }
        chooser.setSelectedFile(null);
    }//GEN-LAST:event_btnBrowseRouteActionPerformed

    private void btnParseRouteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnParseRouteActionPerformed
        
        RouteParser myRoute = new RouteParser(routeFile);
        
        try{
            myRoute.parseFileXSSF();
        }
        catch (IOException e){
            JOptionPane.showMessageDialog(null, "The input file did not load"
                                             + "properly, select a new file.");
            e.printStackTrace();
        }

    }//GEN-LAST:event_btnParseRouteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PayrollGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PayrollGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PayrollGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PayrollGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PayrollGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrowseRoute;
    private javax.swing.JButton btnParseRoute;
    private javax.swing.JButton closeButton;
    private javax.swing.JTextField inputFileTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel parseEquipmentTab;
    private javax.swing.JPanel parsePrintRouteTab;
    private javax.swing.JPanel parseRouteTab;
    // End of variables declaration//GEN-END:variables
   
    // Additional variable declarations
    private JFileChooser chooser;
    private File routeFile;
    private String routeFileName;
    
}
